# Generated by Django 4.1.1 on 2022-10-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fooditem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('calories', models.IntegerField(blank=True)),
                ('protein', models.IntegerField(blank=True)),
                ('carbohydrates', models.IntegerField(blank=True)),
                ('fat', models.IntegerField(blank=True)),
                ('sugar', models.IntegerField(blank=True)),
                ('fibre', models.IntegerField(blank=True)),
            ],
        ),
    ]
