# Generated by Django 4.1.1 on 2022-10-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcaljournal', '0002_alter_fooditem_calories_alter_fooditem_carbohydrates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='Produsent',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
