# Generated by Django 4.1.1 on 2022-10-02 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kcaljournal', '0003_fooditem_produsent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditem',
            old_name='Produsent',
            new_name='produsent',
        ),
    ]
