# Generated by Django 4.1.2 on 2023-01-20 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kcaljournal', '0007_journal_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kcaljournal.fooditem')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kcaljournal.journal')),
            ],
        ),
    ]
