# Generated by Django 4.1.2 on 2023-01-20 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcaljournal', '0008_foodentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodentry',
            name='date',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
    ]
