# Generated by Django 4.1.2 on 2023-01-24 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kcaljournal', '0009_foodentry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodentry',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kcaljournal.journal'),
        ),
    ]
