# Generated by Django 4.1.2 on 2023-01-27 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kcaljournal', '0010_alter_foodentry_journal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='date',
            new_name='date_created',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='text',
        ),
    ]
