# Generated by Django 4.1.2 on 2023-01-28 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kcaljournal', '0011_rename_date_journal_date_created_remove_journal_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodentry',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kcaljournal.journal'),
        ),
    ]
